dataset_path: /fslhome/andreww9/code/original_datasets/BP4D_croppped_MTCNN
# dataset_path: /home/andreww9/groups/grp_face_race/nobackup/autodelete/BP4D_croppped_MTCNN_edges
num_classes: 12
neighbor_num: 4