dataset_path: /home/andreww9/fsl_groups/grp_RVL_AU/code/DISFA_LEFT_cropped_MTCNN
fsrt_dataset_path: /home/andreww9/groups/grp_RVL_AU/nobackup/archive/dataset/fsrt_computed_imgs_zipped
num_classes: 8
neighbor_num: 3